name: Deploy automatico para o servidor

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt update
            - run: sudo apt install -y rsync
            - run: sudo apt install -y openssh-client
            - run: sudo apt install -y secure-delete
            - run: sudo apt install -y sshpass
            - run: mkdir -p ~/.ssh
            - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            - run: chmod 600 ~/.ssh/id_rsa
            - run: rsync -p ${{secrets.SERVER_PASSWORD}} --archive --verbose --compress --delete --copy-as=www-data:www-data -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./ admin@45.148.30.60:/var/www/html/webtech.network
              continue-on-error: true
            - run: sshpass -p "${{secrets.SERVER_PASSWORD}}" sshpass -p "${{secrets.SERVER_PASSWORD}}" ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa admin@45.148.30.60 "sudo chown --recursive www-data:www-data /var/www/html/webtech.network"
            - run: srm ~/.ssh/id_rsa

