name: Deploy automatico para o servidor

env:
    hostname: webtech.network
    username: admin
    destination: /var/www/html/webtech.network
    target_username: www-data
    target_group: www-data
    excluded_items_command: "--exclude .git --exclude .github --exclude .vscode"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # Obtendo o código do repositório
            - uses: actions/checkout@v4

            # Instalando os pacotes necessários
            - run: sudo apt update
            - run: sudo apt install -y rsync
            - run: sudo apt install -y openssh-client
            - run: sudo apt install -y secure-delete
            - run: sudo apt install -y sshpass

            # Obtendo a chave ssh privada
            - run: mkdir -p ~/.ssh
            - run: echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
            - run: chmod 600 ~/.ssh/id_rsa

            # Alterando as permissões do diretório no servidor para poder copiar os arquivos
            - run: sshpass -p "${{secrets.SERVER_PASSWORD}}" ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{env.username}}@${{env.hostname}} "echo \"${{secrets.SERVER_PASSWORD}}\" | sudo -S chown --recursive ${{env.username}} ${{env.destination}}"

            # Sincronizando os arquivos com o servidor
            - run: rsync -p ${{secrets.SERVER_PASSWORD}} --archive --verbose --compress --delete ${{env.excluded_items_command}} -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./ ${{env.username}}@${{env.hostname}}:${{env.destination}}
              continue-on-error: true

            # Alterando as permissões do diretório no servidor para poder ser acessado pelo servidor web
            - run: sshpass -p "${{secrets.SERVER_PASSWORD}}" ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{env.username}}@${{env.hostname}} "echo \"${{secrets.SERVER_PASSWORD}}\" | sudo -S chown --recursive ${{env.target_username}}:${{env.target_group}} ${{env.destination}}"
            
            # Apagando a chave ssh privada
            - run: srm ~/.ssh/id_rsa

            

